version: '3.8'

services:
  randombot:
    image: cabel-random-bot:latest
    restart: always
    networks:
      nginx-network:
        aliases:
          - nginx-cabel-random-bot.xobotun.com-container

networks:
  nginx-network:
    external: true
