version: '3.8'

services:
  carbot:
    image: martian-agro-bot:latest
    restart: always
    networks:
      nginx-network:
        aliases:
          - nginx-rx-martian-agro-bot.xobotun.com-container

networks:
  nginx-network:
    external: true
